# Generated by Django 6.0.4 on 2026-04-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
            ],
        ),
    ]
